:bank_holiday_mondays:
  :england:
   -
    :datetime_field: 2013-05-27
    :description: "Spring bank holiday"
   -
    :datetime_field: 2013-08-26
    :description: "Summer bank holiday"
   -
    :datetime_field: 2014-04-21
    :description: "Easter Monday"
   -
    :datetime_field: 2014-05-05
    :description: "Early May bank holiday"
   -
    :datetime_field: 2014-05-26
    :description: "Spring bank holiday"
   -
    :datetime_field: 2014-08-25
    :description: "Summer bank holiday"
   -
    :datetime_field: 2015-04-06
    :description: "Easter Monday"
   -
    :datetime_field: 2015-05-04
    :description: "Early May bank holiday"
   -
    :datetime_field: 2015-05-25
    :description: "Spring bank holiday"
   -
    :datetime_field: 2015-12-28
    :description: "Boxing Day"
   -
    :datetime_field: 2016-03-28
    :description: "Easter Monday"
   -
    :datetime_field: 2017-12-25
    :description: "Christmas Day"
   -
    :datetime_field: 2018-01-01
    :description: "New Year's Day"
   -
    :datetime_field: 2018-04-02
    :description: "Easter Monday"
   -
    :datetime_field: 2018-05-07
    :description: "Early May bank holiday"
   -
    :datetime_field: 2018-05-28
    :description: "Spring bank holiday"
   -
    :datetime_field: 2018-08-27
    :description: "Summer bank holiday"

  :scotland:
   -
    :datetime_field: 2013-05-27
    :description: "Spring bank holiday"
   -
    :datetime_field: 2013-08-05
    :description: "Summer bank holiday"
   -
    :datetime_field: 2013-12-02
    :description: "substitute for St. Andrew's Day"
   -
    :datetime_field: 2014-05-05
    :description: "Early May bank holiday"
   -
    :datetime_field: 2014-05-26
    :description: "Spring bank holiday"
   -
    :datetime_field: 2014-08-04
    :description: "Summer bank holiday"
   -
    :datetime_field: 2013-12-01
    :description: "substitute for St. Andrew's Day"
   -
    :datetime_field: 2015-05-04
    :description: "Early May bank holiday"
   -
    :datetime_field: 2015-05-25
    :description: "Spring bank holiday"
   -
    :datetime_field: 2015-08-03
    :description: "Summer bank holiday"
   -
    :datetime_field: 2015-11-30
    :description: "St. Andrew's Day"
   -
    :datetime_field: 2015-12-28
    :description: "substitute for Boxing Day"
   -
    :datetime_field: 2017-12-25
    :description: "Christmas Day"
   -
    :datetime_field: 2018-01-01
    :description: "New Year's Day"
   -
    :datetime_field: 2018-05-07
    :description: "Early May bank holiday"
   -
    :datetime_field: 2018-05-28
    :description: "Spring bank holiday"
   -
    :datetime_field: 2018-08-06
    :description: "Summer bank holiday"

  :cyprus:
   -
    :datetime_field: 2013-06-24
    :description: "Whit Monday (Κατακλυσμός)"
   -
    :datetime_field: 2013-10-28
    :description: "Greek National day (Μέρα του ΟΧΙ)"
   -
    :datetime_field: 2014-01-06
    :description: "Epophany (Φώτα)"
   -
    :datetime_field: 2014-03-03
    :description: "Green Monday (Καθαρά Δευτέρα)"
   -
    :datetime_field: 2014-04-21
    :description: "Orthodox Easter Monday (Δευτέρα του Πάσχα)"
   -
    :datetime_field: 2014-06-09
    :description: "Whit Monday (Κατακλυσμός)"
   -
    :datetime_field: 2015-02-23
    :description: "Green Monday (Καθαρά Δευτέρα)"
   -
    :datetime_field: 2015-04-13
    :description: "Orthodox Easter Monday (Δευτέρα του Πάσχα)"
   -
    :datetime_field: 2015-06-01
    :description: "Whit Monday (Κατακλυσμός)"
   -
    :datetime_field: 2016-03-14
    :description: "Green Monday (Καθαρά Δευτέρα)"
   -
    :datetime_field: 2016-05-02
    :description: "Orthodox Easter Monday (Δευτέρα του Πάσχα)"
   -
    :datetime_field: 2016-06-20
    :description: "Whit Monday (Κατακλυσμός)"
   -
    :datetime_field: 2016-08-15
    :description: "Assumption Day, (Κοίμησης της θεοτόκου)"
   -
    :datetime_field: 2016-12-26
    :description: "Boxing Day (Δεύτερη μέρα των Χριστουγέννων)"
   -
    :datetime_field: 2018-01-01
    :description: "New Year's Day (Πρωτοχρονιά)"
   -
    :datetime_field: 2018-02-19
    :description: "Green Monday (Καθαρά Δευτέρα)"
   -
    :datetime_field: 2018-04-09
    :description: "Orthodox Easter Monday (Δευτέρα του Πάσχα)"
   -
    :datetime_field: 2018-05-28
    :description: "Whit Monday (Κατακλυσμός)"
   -
    :datetime_field: 2018-10-01
    :description: "Independence Day (Μέρα Ανεξαρτησίας)"
